### ISSUE TITLE
Assassin Bomb

### ISSUE THREAD

**Issue by Jesus-in-Bottle** [pongstylin/tactics#125]
Thank you for anyone and everyone who worked on this! 

Curious as to if it is possible to add the assassin bomb mechanic?

**Comment by pongstylin** [comment]
It already exists.  Since fat fingers can cover up the screen, the trigger was changed such that you need to long press the flashing attack mode button instead of the assassin's tile until she turns red.  Works the same with mud quake.

**Comment by pongstylin** [comment]
There is an indicator already.  The attack mode button starts flashing.  OG players have figured it out before, but plenty others remained confused.  It is at least an improvement on the original game.
