### ISSUE TITLE
Upgrade Sound Library

### ISSUE THREAD

**Issue by pongstylin** [pongstylin/tactics#22]
The game currently uses an old version of Howler.  Now that we're in a NodeJS environment, we need to replace it with a NodeJS package.  After some review of what is out there, I found some potential candidates:

- Latest version of Howler.js.  It's a great choice because we already use it!
https://www.npmjs.com/package/howler

- This didn't exist when I first created the demo years ago!  Designed to be integrated with PIXI.js.
https://www.npmjs.com/package/pixi-sound

- This also seems to be a solid library with all the required features.
https://www.npmjs.com/package/soundjs

**Comment by latin-programmer** [comment]
Created pull request: Howler upgrade #28
