### ISSUE TITLE
MVP Server-Based PvP

### ISSUE THREAD

**Issue by pongstylin** [pongstylin/tactics#26]
Right now it is possible for people to share their screens and play PvP.  The next milestone is to play PvP with a server handling the communication.

(MVP) User Requirements:
1. User A clicks a public link to start a game.
2. User A is prompted to enter a "display name" if their client is not associated with an account.
3. Upon submitting a "display name", an account is created and associated with the client.
4. User A is then provided with a URL that has been tagged with the created game.
5. User B clicks the URL after User A shares it via email, text, or IM.
6. User B is prompted to enter a "display name" if their client is not associated with an account.
7. Upon submitting a "display name", an account is created and associated with the client.
8. The new game begins and is persisted indefinitely if the players go offline in case they come back.

(FULL) User Requirements:
1. When launching the app, the client will check to see if it already possesses a token.
2. If no token was found, then the user is prompted to provide a display name or login with email and password.
3. If the user provided a display name, then a new account is created without an email or password.
4. Regardless of new or existing account, a token is required to proceed.
5. If the app was launched via a Game URL, then the user is presented with the game board.
6. If the app was not launched via a Game URL, then the user is presented with a lobby where they can chat or see a list of people available to play.
7. For accounts that don't have an email and password, a button will allow a user to register their account so that it may be accessed on other devices.

(FULL) Authentication/Authorization requirements:
1. Valid expired tokens must never require the user to log in to obtain new tokens.  This is necessary for users that do not have log in credentials, but remains a convenience for users that do.
2. For better performance, non-expired tokens must not be checked for validity.
3. More than one client may be logged into the same account at the same time.
4. A given client may only be logged into one account at any given time.
5. Token must be protected against unauthorized use by:
   - Assigning each client unique tokens.
   - Refreshing expired tokens such that old tokens are revoked and cannot be used again.
   - *** Automatically revoking the client's token if an attempt is made to use an old token.
      - This requirement no longer seems advisable after realizing that race conditions between multiple browser tabs can result in the accidental use of an old token.  I do not want such to cause a user to lose their account if they had not verified it with an email address or other authentication provider.
   - Allowing a user to revoke tokens for one or all clients.
   - Keeping track of each client ID / token pair on the server.  (No need to track revoked tokens)

Some comments about implementation, but they are negotiable.

- When using AWS Cognito, explore not providing a username and using whatever username it uses by default.  If a username is required, provide a UUID.  Regardless, the "sub" value (User ID generated by AWS Cognito) will not be communicated to clients.
- A JWT can be used to meet all the authentication/authorization requirements.  But, after the JWT expires, it must be exchanged for a new one - assuming the expired token is still valid.  I think it is best for the client to exchange tokens every time it is launched.  It should also have the ability to unpack the JWT to learn when it expires so that it can proactively exchange tokens again before it expires in the event that the client remains open for longer than the expiration time.  Unpacking a JWT should be possible.  I believe they are not usually encrypted, but rather "signed" so that they can be read, but not modified (e.g. to increase the expiration value) without a secret key.  Every time the JWT is submitted to the server, it checks the signature, but not token validity.
- The secret key used to sign JWT tokens must be accessible to both the authentication service and any other service that accepts JWT tokens.  It may be a single secret key used for all accounts.
- Since a JWT can be unpacked, it must only contain "claims" that a client may read.  But it should also contain sufficient details for server-side validation.  The claims should only include data that is relevant for authentication and authorization as opposed to user profile or session data.  Some JWT claims are part of the JWT specification and are marked with "(spec)".
   - exp: (spec) The timestamp when the JWT will expire.  Very important.
   - iat: (spec) The timestamp when the JWT was issued.  This can be used by the client to adjust for an inaccurate time on the local system.
   - sub: (spec) The account ID.  This may be the username generated by AWS Cognito (or UUID if generation is not possible or preferable)
   - client_id: The unique ID assigned to the client.  If a client tries to exchange a revoked (or never-issued) JWT, then we need this value to revoke the current token for the client that was compromised.
- Revoking a client's token may not immediately revoke access to the account.  If a token has not expired, it is not checked for validity and may be used.  I recommend that the token is only checked for validity before it is exchanged for a new one.  Since the client may exchange tokens (expired or not) every time it is launched, validity checking would occur with every launch of the client.  Even so, the expiration value should be no longer than an hour and may be less.
- A client submits the JWT token using an "Authorization" header.  This applies to all HTTP endpoints including both the authentication and game services.

Two people are assigned to this very large issue.  I expect Enijar will be responsible for server-side logic while I will be responsible for client-side logic.

**Comment by Merethiel** [comment]
I will work with you to make this multiplayer if you'd like. Please get in contact with me. So rather than relying on sharing we can have actual multiplayer game play going on based on what you described above.

**Comment by latin-programmer** [comment]
@Merethiel Great to hear you would like to contribute. We have moved a lot of the discussion to our discord, including the multi-player design. Please join us there:
https://discord.gg/YV4dZr

If the link expires, I can send you a new one

**Comment by fransyozef** [comment]
What is the progress on this? I was thinking to create a server with nestjs.com

**Comment by pongstylin** [comment]
I never heard of NestJS, but it seems to be a very capable framework.  I started out using the socket.io library and decided I didn't like it, so I've created a roll-my-own framework built on WebSocket.  All RPC and event communication is done over WebSocket.  This repository already has sufficient code to play server-based games.  But I'm still adding a few more minor features and fixing bugs before deploying a beta server at the end of the month.

In the meantime, I'd appreciate any effort on your part to find and fix or report bugs.

**Comment by seand88** [comment]
I am interested in setting up a server to help support the game. 
I have experiencing running linux servers and databases. 

I am trying to build the game on windows but getting some errors. Will report back once I can get it compiling.

**Comment by pongstylin** [comment]
@seand88 
Minimum NodeJS v10.

I'll update the README to make this clear.

**Comment by pongstylin** [comment]
I've launched a beta server at this URL.
https://tactics-beta.taorankings.com

I'm closing out this ticket since the fundamentals are in place.  I'm just putting it through beta testing to iron out bugs and add a few more essential features before lifting the beta status.
