### ISSUE TITLE
Use ES6 class and module syntax

### ISSUE THREAD

**Issue by pongstylin** [pongstylin/tactics#3]
The game source code does not use ES6 classes nor make use of ES6 module syntax.  Refactor the game modules to use this syntax without altering the game experience.

When using ES6 constructs, make sure they are compatible with modern browsers.  If necessary, the "webpack" module can be used to add shims or otherwise transform the code to something browsers can handle.

**Comment by Enijar** [comment]
I started working on this last night but it seems a lot of the code is tightly coupled to the utils/event.js class. This will take some time to refactor into a more class-oriented structure. I'll draw up a plan on the overall structure when I get back home from work, but I'm thinking something like this:

### Structure
/src/Entities

#### Unit Classes
These represent the data for each unit, such as attack, armour, etc. These classes will be instantiated when the game is started and properties such as hp will be tracked inside them.

\- /Unit
-- Beserker.js
-- Cleric.js
-- Knight.js
-- BaseUnit.js *All Unit classes extend this, sharing common functionality*

\- /Emitter
-- UnitEmitter.js
-- BaseEmitter.js *All Emitter classes extend this, sharing common functionality*

These represent the "event system". Any class may extend these objects to provide event emitters. Emitters will have the ability to listener to and fire events in the system. For example a Cleric unit class might look like this (with the emitter)

```js
class UnitEmitter extends BaseEmitter {
  on(event, fn) {
    // Listen to event with given function
  }

  emit(event, ...args) {
    // Trigger the given event with args
  }
}

class BaseUnit extends UnitEmitter {
  // Extend UnitEmitter and add common functionality for all Unit classes

  heal() {
    // Example of heal method.
    this.hp = Math.min(this.hp + 24, this.maxHp);
  }
}

class Cleric extends BaseUnit {
  heal() {
    this.emit('heal');

    // Notify all ally units that they are to be healed by n HP points.
  }
}

// Example of other user listening to the heal event
class Beserker extends BaseUnit {
  constructor() {
    this.on('heal', () => this.heal());
  }
}
```

**Comment by pongstylin** [comment]
Inheritance may not be the best tool for adding event functionality to a class. I'm thinking that a trait/role/interface may be better. It is basically the idea of decorating a class prototype with methods that implement a specific interface or role (different terms are used by different languages to convey the concept).

**Comment by Enijar** [comment]
Agreed, we could, for example, make an emitter decorator, which any class can inherit from a decorator. Something like this.

```js
function emitter (target) {
  target.prototype.emit = (event, ...args) {
    // Code to handle emit method.
  }
}

@emitter
class Cleric extends BaseUnit {
  heal() {
    this.emit('heal');
    // Notify all ally units that they are to be healed by n HP points.
  }
}
```

**Comment by pongstylin** [comment]
Wow, I have never seen that syntax for applying a decorator before. And, no wonder. It is not even an official feature yet -- it is still a proposal. It is not implemented by any browsers, but that is ok. You can configure webpack to use the babel transpiler and install the proposal decorator plugin. That way the decorator code will be replaced by browser-compatible code when building bundles. You are welcome to give it a shot. I've used babel before, even if I have not used this plugin. Babel works well.

Bear in mind that you could decorate the base unit class instead of all of the specific classes. I just did not want it to "inherit" the functionality. I'm fine with the specific classes inheriting the functionality from the base class.

**Comment by pongstylin** [comment]
The majority of classes are now converted over to use ES6 module and class syntax.  This was necessary for a clean server-side integration of game state management.  Even though not all classes have been converted, I'm closing out this issue since there is no urgency for further conversion work.
