### ISSUE TITLE
Status bar broken when unit is killed

### ISSUE THREAD

**Issue by Villarrealized** [pongstylin/tactics#33]
First of all, I am so excited to see this project. I loved playing TAO back in the day and hoped it would someday be resurrected. I played around with the idea of trying to do it but never got around to it. Really awesome work so far!

As I was playing around with it just now, I noticed that there is an issue with the status bar breaking when a unit is killed.
<img width="1737" alt="screen shot 2019-02-13 at 11 22 09 am" src="https://user-images.githubusercontent.com/5977736/52735735-7add7380-2f85-11e9-9f6d-87bc20e706ef.png">
![screen shot 2019-02-13 at 11 23 49 am](https://user-images.githubusercontent.com/5977736/52735743-80d35480-2f85-11e9-9b11-d48de12bfad9.png)

I hope to be able to contribute to the project sometime soon. I'll try to take a look at the source soon and get up to speed.

**Comment by pongstylin** [comment]
Goodness.  You found that bug only a couple hours after it was introduced.  Good catch.
