### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by Enijar** [pongstylin/tactics#4]
There should be some sort of linter config in the project root to reduce issues due to code style conflicts when merging pull requests. Thoughts?

**Comment by pongstylin** [comment]
I think a linter would be great now that it is a team project. Good call. Make sure it can be easily used in a popular editor (e.g. Atom). It might also be used in a test that can be run to make sure new code changes are lint free before merging.

**Comment by Enijar** [comment]
I was thinking [ESLint](https://eslint.org/), as that seems most popular for JS projects around Github. We can also setup [TravisCI](https://travis-ci.org/) for checking code when pull requests are made.

**Comment by pongstylin** [comment]
I'm closing this out unless somebody really wants to tackle this.  The urgency is low since pull requests are rare and I am able to push back on any major style violations.
