### ISSUE TITLE
async functions in data adapters

### ISSUE THREAD

**Issue by seand88** [pongstylin/tactics#41]
I would like to contribute the mysqladapter code i have been working on but it requires that some calls to dataadapter methods be async.

here is an example method from my data adapter which returns a promise.

```
  async createGame(stateData) {
    let insertQuery = "INSERT INTO game ( name, created_by) values ( ?, ? )";
    return this.query(insertQuery, [stateData.name, stateData.createdBy]).then( result => {
        //create game object with new game id and save to database
       let gameId = result.insertId;
       stateData.id = gameId;
       let game = Game.create(stateData);
       return this.saveGame(game).then( res =>{
         return gameId;
       }, err => { return 0; })         
    }, err =>{
       return 0;
    })
  }
```

example await call from the game service
```
let gameId = await dataAdapter.createGame(stateData);
```
I think this would be a good convention going forward for the adapters, so it can handle async operations. It looks like the file operations are all synchronous.

Would like some opinions before I open up any pull request.

Thanks
Sean

**Comment by pongstylin** [comment]
I agree.  All (not some) data operations should be async.  This requires a little refactoring of the file adapter and the calling code.  Use of async/await syntax is perfectly fine.

On a side note, if you aren't already, you can use the server config JSON file to configure the MySQL data adapter, e.g. database name, location, auth credentials, etc.
