### ISSUE TITLE
Manage WebSockets Across Multiple Tabs

### ISSUE THREAD

**Issue by pongstylin** [pongstylin/tactics#45]
Right now a WebSocket connection is created on every tab.  This connection can remain open even if tabs are hidden.  This environment allows a single user to establish multiple connections with the server.  This can be an unnecessary burden on the server.  There are changes that would improve the situation:

- For browsers that support it, a Shared Worker can be accessed from multiple tabs.  This worker will manage the WebSocket connection and proxy messages between the server and the tabs.
- If the page is talking directly to the server and is not using a Shared Worker proxy for any reason, the Page LifeCycle API is used to detect when the page becomes "Hidden" or "Active/Passive" and close and reopen the server connection in response.

**Comment by Enijar** [comment]
For older browsers, you can open/close WS connections using `window.onfocus` and `window.onblur `.
