### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by BunPrinceton** [pongstylin/tactics#61]
Macro keys for pre set formations - V formation, etc.
Macro for retreat all - straight line back
Macro for advance all - straight line forward
Additional neutral pills:
Speed Boost
Limited Invulnerability
Wormhole entrance and exit

**Comment by pongstylin** [comment]
The suggestions seems to be meant for another game.  For example, you say "Additional neutral pills", but there are no existing "neutral pills".

**Comment by BunPrinceton** [comment]
Sorry I meant to post these on a different game page xD my bad
