### ISSUE TITLE
Auto-refresh game list page

### ISSUE THREAD

**Issue by pongstylin** [pongstylin/tactics#71]
It should not be necessary to manually refresh the game list page repeatedly in anticipation of a game being created or an opponent submitting their turn.  Ideally, this should be implemented as a server push message, but it is acceptable for the client to poll every 5 seconds instead.

**Comment by MainShayne233** [comment]
Started taking a stab at this, rolling with a polling method for now.

Curious: how would you feel about using a rendering framework like [preact](https://github.com/preactjs/preact), [vue](https://github.com/vuejs/vue), or even [elm](https://elm-lang.org/)? 

It could simplify the DOM updating code. Using one of these, all we'd need to do is update a list of games upon a successful fetch and the page would automatically re-render itself.

**Comment by pongstylin** [comment]
The website included in this repo is just an example of how to launch the game with basic capabilities for arranging games.  It is an open game engine that I expect people will fork and develop their own website using Vue or React or whatever they want.  Certainly I plan to use Vue when I fork my own repo to develop the commercial server.  But for the example site, we will keep it simple and unopinionated

**Comment by MainShayne233** [comment]
Cool, that makes sense! I'll stick with the current DOM updating code then. :slightly_smiling_face:

**Comment by pongstylin** [comment]
Are you on the TAO discord chat... or at least the TAO Facebook group?
